anguage: php

php:
  - 5.3
  - 5.4

before_script:
  - curl -sS https://getcomposer.org/installer | php
  - composer install

script: phpunit -c app/

notifications:
  email:
    - julien@eetserious.com