language: php

php:
#  - 5.3
  - 5.4

before_script:
  - curl -s http://getcomposer.org/installer | php --
  - php composer.phar install --dev
#  - mysql -p -h localhost symfony < mysql/symfony.sql

script: phpunit -c app/

notifications:
  email:
    - julien@eetserious.com
