language: php

php:
#  - 5.3
  - 5.4

before_script:
  - mysql -e 'create database IF NOT EXISTS symfony;' -uroot
  - curl -s http://getcomposer.org/installer | php --
  - php composer.phar install --dev
  - cp app/config/config_test.yml.travis app/config/config_test.yml
  - php app/console --env=test doctrine:schema:update --force


script: phpunit -c app/

notifications:
  email:
    - julien@eetserious.com
