hetic_blog_post:
    path:     /
    defaults: { _controller: "HeticBlogBundle:Post:index" }

hetic_blog_post_show:
    path:     /{id}/show
    defaults: { _controller: "HeticBlogBundle:Post:show" }

hetic_blog_post_new:
    path:     /new
    defaults: { _controller: "HeticBlogBundle:Post:new" }

hetic_blog_post_create:
    path:     /create
    defaults: { _controller: "HeticBlogBundle:Post:create" }
    requirements: { _method: post }

hetic_blog_post_edit:
    path:     /{id}/edit
    defaults: { _controller: "HeticBlogBundle:Post:edit" }

hetic_blog_post_update:
    path:     /{id}/update
    defaults: { _controller: "HeticBlogBundle:Post:update" }
    requirements: { _method: post|put }

hetic_blog_post_delete:
    path:     /{id}/delete
    defaults: { _controller: "HeticBlogBundle:Post:delete" }
    requirements: { _method: post|delete }
