hetic_site:
    resource: "@HeticSiteBundle/Resources/config/routing.yml"
    prefix:   /g2

hetic_blog:
    resource: "@HeticBlogBundle/Resources/config/routing.yml"
    prefix:   /g1

hetic_public:
    resource: "@HeticPublicBundle/Resources/config/routing.yml"
    prefix:   /

