security:
    access_denied_url:    /access-interdis # Exemple: /foo/error403

    encoders:
        Symfony\Component\Security\Core\User\User:
          algorithm:   sha1
          iterations: 1
          encode_as_base64: false

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: "%password_user%", roles: [ 'ROLE_USER' ] }
                    admin: { password: "%password_admin%", roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        site_login:
            pattern:  ^/login$
            security: false
        main:
            pattern:    ^/
            anonymous:  ~
            form_login:
                check_path: /login_check
                login_path: /login
                csrf_provider: form.csrf_provider
                always_use_default_target_path: true
                default_target_path:            /
#                use_referer: true
#                use_forward: true

            logout:
                path:   /logout
                target: /
