Tag:
    type: entity
    table: tag
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        word:
            type: string
            nullable: true
            length: 300
            fixed: false
            comment: ''
    manyToMany:
        post:
            targetEntity: Post
            cascade: {  }
            mappedBy: tag
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
