hetic_public_homepage:
    path:     /
    defaults: { _controller: HeticPublicBundle:Default:index }
    requirements:
      _method:  GET

hetic_public_response:
    path:     /message
    defaults: { _controller: HeticPublicBundle:Default:message }
    requirements:
      _method:  GET

hetic_public_form:
    path:     /form
    defaults: { _controller: HeticPublicBundle:Default:form }
    requirements:
      _method:  GET|POST

hetic_public_createpost:
    path:     /create-post
    defaults: { _controller: HeticPublicBundle:Post:create }
    requirements:
      _method:  GET|POST

hetic_public_redirection:
    path:     /redirection
    defaults: { _controller: HeticPublicBundle:Default:redirection }
    requirements:
      _method:  GET

hetic_public_forward:
    path:     /forward
    defaults: { _controller: HeticPublicBundle:Default:forward }
    requirements:
      _method:  GET

hetic_public_notfound:
    path:     /notfound
    defaults: { _controller: HeticPublicBundle:Default:notfound }
    requirements:
      _method:  GET

hetic_public_messageflash:
    path:     /messageflash
    defaults: { _controller: HeticPublicBundle:Default:messageflash }
    requirements:
      _method:  GET

notification:
    path:     /notification/{type}
    defaults: { _controller: HeticPublicBundle:Default:notification, type:success }
    requirements:
      _method:  GET

twig:
    path:     /twig
    defaults: { _controller: HeticPublicBundle:Default:twig }
    requirements:
      _method:  GET

voirpost:
    path:     /voir-post/{id}
    defaults: { _controller: HeticPublicBundle:Post:voirPost }
    requirements:
      _method:  GET

createpost:
    path:     /create-post/{title}
    defaults: { _controller: HeticPublicBundle:Post:createPost }
    requirements:
      _method:  GET|POST|PUT|DELETE|PATCH

denied:
    path:     /access-interdis
    defaults: { _controller: HeticPublicBundle:Auth:forbidden }
    requirements:
      _method:  GET

login:
    path:     /login
    defaults: { _controller: HeticPublicBundle:Auth:login }
    requirements:
          _method:  GET|POST|PUT
logout:
    path:     /logout

login_check:
    path:     /login_check
    defaults: { _controller: HeticPublicBundle:Auth:login }
    requirements:
      _method:  POST

posts_http:
    path:     /posts-http
    defaults: { _controller: HeticPublicBundle:Post:index }
    requirements:
      _method:  GET

updatepost:
    path:     /update-post/{id}/{title}
    defaults: { _controller: HeticPublicBundle:Post:updatePost }
    requirements:
      _method:  POST
