<?php

namespace Hetic\PublicBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{


    /**
     * Get post by id desc
     * @return array
     */
    public function getPostsByIdDesc()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM HeticPublicBundle:Post p ORDER BY p.id DESC'
            )
            ->getResult();
    }



    /**
     * Get post by Title
     * @return array
     */
    public function getPostsByTitle()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM HeticPublicBundle:Post p ORDER BY p.title ASC'
            )
            ->getResult();
    }

    /**
     * Get post visible
     * @return array
     */
    public function getPostsVisible()
    {
        return $this->getEntityManager()
            ->createQueryBuilder('p')
            ->select('p')
            ->from('HeticPublicBundle:Post','p')
            ->where('p.visible = :visible')
            ->orderBy('p.dateCreated', 'DESC')
            ->getQuery()
            ->setParameter('visible', true)
            ->getResult();
    }


}
