<?php

namespace Hetic\PublicBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{


    /**
     * Get post by Title
     * @return array
     */
    public function getPostsByTitle()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM HeticPublicBundle:Post p ORDER BY p.title ASC'
            )
            ->getResult();
    }
}
